"use client";

import { useEffect, useState } from "react";

type Application = { id: string; status: string; created_at: string; jobs: { title: string; city: string | null; province: string | null; work_mode: string | null; company_profiles: { name: string } | { name: string }[] | null } | { title: string; city: string | null; province: string | null; work_mode: string | null; company_profiles: { name: string } | { name: string }[] | null }[] | null };
const labels: Record<string, string> = { submitted: "Submetida", screening: "Em análise", interview: "Entrevista", offer: "Proposta", accepted: "Aceite", rejected: "Não seleccionada" };

export default function ApplicationsPage() {
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/applications").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setApplications(body.applications ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  return <main><header className="site-header"><a href="/" className="brand" aria-label="OkutiJobs — início"><span className="brand-lockup"><span className="brand-symbol"><img src="https://wmkxeqghopmbsfwptpzq.supabase.co/storage/v1/object/public/brand-assets/okutijobs-new-mark.png" alt="" /></span><span className="brand-word">Okuti<span>Jobs</span></span></span></a><nav className="desktop-nav"><a href="/vagas">Vagas</a><a href="/candidato">Área do candidato</a></nav><div className="header-actions"><a className="header-login" href="/candidato">Voltar à área</a></div></header><section className="portal-wrap application-page"><div className="portal-heading"><div><p className="eyebrow">Área do candidato</p><h1>As minhas candidaturas.</h1><p className="lede">Acompanhe o estado de cada oportunidade a partir dos registos reais da plataforma.</p></div><a className="button button-orange" href="/vagas">Explorar vagas <span>↗</span></a></div>{loading && <div className="empty-state"><h3>A carregar candidaturas…</h3><p>Estamos a consultar o seu histórico seguro.</p></div>}{error && <div className="empty-state"><h3>{error}</h3><p>Inicie sessão como candidato e tente novamente.</p><a className="button button-dark" href="/login">Iniciar sessão</a></div>}{!loading && !error && applications.length === 0 && <div className="empty-state"><h3>Ainda não tem candidaturas.</h3><p>Explore as vagas disponíveis e envie a sua primeira candidatura.</p><a className="button button-orange" href="/vagas">Ver vagas <span>↗</span></a></div>}{!loading && !error && applications.length > 0 && <div className="application-list">{applications.map((application) => { const job = Array.isArray(application.jobs) ? application.jobs[0] : application.jobs; const company = job && (Array.isArray(job.company_profiles) ? job.company_profiles[0]?.name : job.company_profiles?.name); return <article className="application-row" key={application.id}><div><p className="eyebrow">{company || "Empresa"}</p><h2>{job?.title || "Oportunidade"}</h2><p>{[job?.city, job?.province, job?.work_mode].filter(Boolean).join(" · ") || "Detalhes em actualização"}</p></div><div className="application-status"><strong>{labels[application.status] || application.status}</strong><small>{new Date(application.created_at).toLocaleDateString("pt-PT")}</small></div></article>; })}</div>}</section></main>;
}
