"use client";

import { useState } from "react";
type AssessmentScore = { type: string; language: string | null; score: number; level: string | null };
type Result = { candidateId: string; name: string; score: number; recommendation: "strong_match" | "review" | "low_match"; strengths: string[]; gaps: string[]; interviewTopics: string[]; assessments?: AssessmentScore[] };
const assessmentLabel: Record<string, string> = { language: "Idioma", knowledge: "Conhecimento", psychometric: "Psicotécnico" };
function average(values: number[]) { return values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) : 0; }

export function AiTriageButton({ jobId }: { jobId: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [results, setResults] = useState<Result[] | null>(null);
  async function run() { setBusy(true); setError(""); try { const response = await fetch("/api/company/ai-triage", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jobId }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setError(body.error || "Não foi possível concluir a triagem."); setResults(body.results || []); } catch { setError("Não foi possível contactar o serviço de triagem."); } finally { setBusy(false); } }
  const aiAverage = average((results ?? []).map((result) => result.score)); const testScores = (results ?? []).flatMap((result) => result.assessments ?? []); const testAverage = average(testScores.map((item) => item.score));
  const flow = [{ label: "Compatibilidade IA", value: aiAverage, tone: "ai" }, { label: "Resultados dos testes", value: testAverage, tone: "tests" }, { label: "Forte correspondência", value: results?.length ? Math.round(((results ?? []).filter((item) => item.recommendation === "strong_match").length / results.length) * 100) : 0, tone: "strong" }, { label: "Revisão humana", value: results?.length ? Math.round(((results ?? []).filter((item) => item.recommendation === "review").length / results.length) * 100) : 0, tone: "review" }];
  return <div className="ai-triage-box"><button type="button" className="button button-dark" onClick={run} disabled={busy}>{busy ? "A analisar candidatos…" : "Triar candidatos com IA ↗"}</button>{error ? <p className="form-error" role="alert">{error}</p> : null}{results ? <div className="ai-triage-results"><div className="ai-triage-heading"><strong>Ranking assistido por IA</strong><span>Reveja antes de contactar ou excluir qualquer candidato.</span></div><div className="triage-flow" aria-label="Fluxo de compatibilidade da triagem IA"><div className="triage-flow-heading"><div><p className="eyebrow">Fluxo de compatibilidade</p><strong>IA + avaliações verificadas</strong></div><span>{results.length} candidato{results.length === 1 ? "" : "s"}</span></div>{flow.map((item) => <div className="triage-flow-row" key={item.label}><div><span>{item.label}</span><b>{item.value}%</b></div><div className="triage-flow-track"><i className={item.tone} style={{ width: `${item.value}%` }} /></div></div>)}<small>Os testes são complementares e nunca substituem a análise humana do currículo e da entrevista.</small></div>{results.length ? results.map((result, index) => <article className="ai-triage-result" key={result.candidateId}><div className="ai-triage-rank"><b>#{index + 1}</b><strong>{result.score}%</strong></div><div><h3>{result.name}</h3><span className={`triage-badge ${result.recommendation}`}>{result.recommendation === "strong_match" ? "Forte correspondência" : result.recommendation === "review" ? "Revisão humana" : "Correspondência baixa"}</span>{result.assessments?.length ? <p className="triage-assessments"><b>Testes:</b> {result.assessments.map((item) => `${assessmentLabel[item.type] ?? item.type} ${item.score}%`).join(" · ")}</p> : null}<p><b>Pontos fortes:</b> {result.strengths.join(" · ") || "Por confirmar"}</p>{result.gaps.length ? <p className="triage-gap"><b>Lacunas:</b> {result.gaps.join(" · ")}</p> : null}<small><b>Temas para entrevista:</b> {result.interviewTopics.join(" · ") || "A definir"}</small></div></article>) : <p className="empty-state">Ainda não existem candidaturas para esta vaga.</p>}<small className="ai-disclaimer">A IA organiza os dados declarados. A decisão final é sempre da empresa e deve respeitar critérios justos e verificáveis.</small></div> : null}</div>;
}
