"use client";

export type CompanyStatisticsData = {
  jobs: Array<{ id: string; title: string; status: string; applications: number }>;
  totals: { jobs: number; published: number; applications: number; activeApplications: number; average: number; lastSevenDays: number };
  statuses: Array<{ label: string; value: number; tone: string }>;
  days: Array<{ label: string; value: number }>;
};

export function CompanyStatistics({ data }: { data: CompanyStatisticsData }) {
  const maxDay = Math.max(...data.days.map((day) => day.value), 1);
  const maxJob = Math.max(...data.jobs.map((job) => job.applications), 1);
  return <main><section className="portal-wrap statistics-page"><div className="portal-heading"><div><p className="eyebrow">Inteligência de recrutamento</p><h1>Estatísticas das suas vagas.</h1><p className="lede">Acompanhe o alcance das oportunidades, o volume de candidaturas e a evolução do seu processo de selecção.</p></div><a className="button button-dark" href="/empresa">← Voltar ao painel</a></div><section className="statistics-kpis"><article><span>Vagas anunciadas</span><strong>{data.totals.jobs}</strong><small>{data.totals.published} publicadas</small></article><article><span>Candidaturas recebidas</span><strong>{data.totals.applications}</strong><small>Em todos os anúncios</small></article><article><span>Processos activos</span><strong>{data.totals.activeApplications}</strong><small>Em análise ou entrevista</small></article><article><span>Média por vaga</span><strong>{data.totals.average}</strong><small>Candidaturas recebidas</small></article></section><section className="statistics-grid"><article className="statistics-card statistics-trend"><div className="statistics-card-heading"><div><p className="eyebrow">Últimos 7 dias</p><h2>Interesse nas suas vagas.</h2></div><span className="statistics-live">Dados actualizados</span></div><div className="statistics-chart" aria-label="Candidaturas nos últimos sete dias">{data.days.map((day) => <div className="statistics-column" key={day.label}><strong>{day.value}</strong><div className="statistics-bar-track"><span style={{ height: `${Math.max((day.value / maxDay) * 100, day.value ? 10 : 3)}%` }} /></div><small>{day.label}</small></div>)}</div></article><article className="statistics-card"><div className="statistics-card-heading"><div><p className="eyebrow">Estado dos processos</p><h2>Pipeline actual.</h2></div></div><div className="statistics-status-list">{data.statuses.map((status) => <div className="statistics-status-row" key={status.label}><span><i className={status.tone} />{status.label}</span><strong>{status.value}</strong></div>)}</div></article></section><section className="statistics-card statistics-jobs"><div className="statistics-card-heading"><div><p className="eyebrow">Desempenho por anúncio</p><h2>As vagas com maior procura.</h2></div><a className="text-link" href="/pagina-empresas">Criar nova vaga <span>↗</span></a></div>{data.jobs.length ? <div className="statistics-job-list">{data.jobs.map((job) => <div className="statistics-job-row" key={job.id}><div><strong>{job.title}</strong><small>{job.status === "published" ? "Publicada" : job.status}</small></div><div className="statistics-job-value"><strong>{job.applications}</strong><span>candidaturas</span><div><i style={{ width: `${Math.max((job.applications / maxJob) * 100, job.applications ? 8 : 0)}%` }} /></div></div></div>)}</div> : <div className="empty-state"><h3>Ainda não existem vagas.</h3><p>Publique a primeira oportunidade para começar a acompanhar o desempenho.</p></div>}</section></section></main>;
}
