"use client";
import { useState } from "react";
import { CandidateServiceRequestModal, type CandidateConsultingService } from "@/components/CandidateServiceRequestModal";
import type { CvReview } from "@/lib/cv-review";

const requestService: CandidateConsultingService = { title: "Novo CV profissional", text: "Pedido de elaboração de um novo CV após análise", price: "A confirmar", action: "Pedir novo CV" };

export function CvReviewExperience() {
  const [profileText, setProfileText] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [review, setReview] = useState<CvReview | null>(null);
  const [status, setStatus] = useState<"idle" | "uploading" | "analysing" | "error">("idle");
  const [error, setError] = useState("");
  const [requestOpen, setRequestOpen] = useState(false);
  async function analyse(event: React.FormEvent) {
    event.preventDefault(); setError(""); setReview(null);
    if (!file && profileText.trim().length < 40) { setStatus("error"); setError("Anexe um CV no seu perfil ou escreva pelo menos 40 caracteres sobre o seu percurso."); return; }
    try {
      if (file) { setStatus("uploading"); const form = new FormData(); form.append("file", file); const upload = await fetch("/api/candidate/cv", { method: "POST", body: form }); if (!upload.ok) { const body = await upload.json().catch(() => ({})); throw new Error(body.error || "Inicie sessão para anexar o CV ao seu perfil."); } }
      setStatus("analysing"); const response = await fetch("/api/cv-review", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileText: profileText.trim() || "Analisa o CV profissional anexado ao meu perfil e identifica pontos fortes, lacunas e recomendações." }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Não foi possível concluir a análise."); setReview(body.review); setStatus("idle");
    } catch (reason) { setStatus("error"); setError(reason instanceof Error ? reason.message : "Não foi possível analisar o CV."); }
  }
  return <section className="cv-review-experience"><div className="cv-review-intro"><p className="eyebrow">Análise inteligente OkutiJobs</p><h2>Descubra o que o seu CV comunica.</h2><p>Anexe o seu CV no perfil ou escreva aqui a sua experiência. O Gemini analisa clareza, completude, impacto e compatibilidade com sistemas ATS.</p></div><form className="cv-review-form" onSubmit={analyse}><label className="cv-review-upload"><input type="file" accept=".pdf,application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><span className="cv-upload-icon">↑</span><strong>{file ? file.name : "Anexar CV em PDF"}</strong><small>{file ? "Ficheiro seleccionado" : "Até 10 MB · precisa de sessão iniciada para guardar no perfil"}</small></label><div className="cv-review-or"><span>ou escreva as informações</span></div><label className="cv-review-text"><span>Experiência, formação, competências e conquistas</span><textarea rows={8} value={profileText} onChange={(event) => setProfileText(event.target.value)} placeholder="Ex.: Sou técnico de contabilidade com 5 anos de experiência..." /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-orange" disabled={status === "uploading" || status === "analysing"}>{status === "uploading" ? "A guardar CV…" : status === "analysing" ? "O Gemini está a analisar…" : "Analisar o meu CV ↗"}</button></form>{status === "analysing" && <div className="cv-review-status"><span className="status-pulse"></span><strong>O Gemini está a rever o seu percurso.</strong><small>A avaliar clareza, competências, impacto e pontos a melhorar…</small></div>}{review && <div className="cv-review-result"><div className="cv-score-panel"><span className="eyebrow">Pontuação geral</span><strong>{review.score}<small>/100</small></strong><p>{review.summary}</p><button type="button" className="button button-orange" onClick={() => setRequestOpen(true)}>Pedir um novo CV ↗</button><button type="button" className="cv-print-button" onClick={() => window.print()}>Guardar análise em PDF</button></div><div className="cv-stat-grid">{[["Completude",review.stats.completeness],["Clareza",review.stats.clarity],["ATS",review.stats.ats],["Impacto",review.stats.impact]].map(([label,value]) => <div key={String(label)}><span>{label}</span><strong>{value}%</strong><i><b style={{ width: `${value}%` }} /></i></div>)}</div><div className="cv-review-columns"><div><h3>O que está bem</h3><ul>{review.strengths.map((item) => <li key={item}>✓ {item}</li>)}</ul></div><div><h3>O que pode melhorar</h3><ul>{review.gaps.map((item) => <li key={item}>! {item}</li>)}</ul></div><div><h3>Recomendações</h3><ul>{review.recommendations.map((item) => <li key={item}>→ {item}</li>)}</ul></div></div></div>}{requestOpen && <CandidateServiceRequestModal service={requestService} onClose={() => setRequestOpen(false)} />}</section>;
}
