"use client";

import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { useMemo, useState } from "react";

export type Job = { id: string; slug?: string; title: string; company: string; place: string; mode: string; area: string; contract: string; salaryKz?: number | null; experienceYears?: number | null; description?: string; requirements?: string | null };
type Course = { title: string; area: string; level: string; mode: string; duration: string };

const courses: Course[] = [
  { title: "Excel profissional para negócios", area: "Escritório", level: "Intermédio", mode: "Online", duration: "12 horas" },
  { title: "Contabilidade geral e financeira", area: "Contabilidade", level: "Fundamentos", mode: "Híbrido", duration: "20 horas" },
  { title: "Vendas consultivas e negociação", area: "Vendas", level: "Avançado", mode: "Presencial", duration: "16 horas" },
  { title: "Liderança de equipas de alto desempenho", area: "Liderança", level: "Executivo", mode: "Híbrido", duration: "10 horas" },
  { title: "Atendimento ao cliente", area: "Soft Skills", level: "Fundamentos", mode: "Online", duration: "8 horas" },
  { title: "Comunicação profissional", area: "Soft Skills", level: "Intermédio", mode: "Online", duration: "8 horas" },
  { title: "Gestão de projectos", area: "Gestão", level: "Intermédio", mode: "Híbrido", duration: "18 horas" },
  { title: "Literacia digital e produtividade", area: "Escritório", level: "Fundamentos", mode: "Online", duration: "6 horas" },
];

function Header() { return <SiteHeader />; }

export function ApplicationModal({ job, onClose }: { job: Job; onClose: () => void }) {
  const [confirmed, setConfirmed] = useState(false); const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!confirmed) { setState("error"); setMessage("Confirme que o seu perfil e CV estão actualizados antes de continuar."); return; } setState("loading"); const response = await fetch("/api/applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jobId: job.id }) }); const body = await response.json().catch(() => ({})); if (response.ok) { setState("success"); setMessage("A sua candidatura foi registada com sucesso."); } else { setState("error"); setMessage(body.error || "Não foi possível enviar a candidatura."); } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="application-modal" role="dialog" aria-modal="true" aria-labelledby="application-title"><button className="modal-close" onClick={onClose} aria-label="Fechar formulário">×</button>{state === "success" ? <div className="modal-success"><span className="success-mark">✓</span><p className="eyebrow">Candidatura enviada</p><h2 id="application-title">Boa sorte no próximo passo.</h2><p>{message}</p><button className="button button-dark" onClick={onClose}>Continuar a explorar</button></div> : <><p className="eyebrow">Candidatura rápida</p><h2 id="application-title">{job.title}</h2><p className="modal-company">{job.company} · {job.place || "Localização a confirmar"}</p><div className="modal-summary"><strong>O que acontece agora?</strong><span>Usaremos o seu perfil e o CV privado guardado na conta para apresentar a candidatura à empresa.</span></div><form onSubmit={submit}><label className="modal-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /> <span>Confirmo que o meu perfil está actualizado e autorizo o envio desta candidatura.</span></label>{message && <p className="form-message" role="alert">{message}</p>}<div className="modal-actions"><button type="button" className="button button-light" onClick={onClose}>Cancelar</button><button type="submit" className="button button-orange" disabled={state === "loading"}>{state === "loading" ? "A enviar…" : "Enviar candidatura ↗"}</button></div></form></>}</section></div>;
}

export function JobsCatalog({ jobs }: { jobs: Job[] }) {
  const [query, setQuery] = useState(""); const [area, setArea] = useState("Todas"); const [mode, setMode] = useState("Todos"); const [salary, setSalary] = useState("any"); const [experience, setExperience] = useState("any"); const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const areas = useMemo(() => ["Todas", ...Array.from(new Set(jobs.map((job) => job.area).filter(Boolean)))], [jobs]); const modes = useMemo(() => ["Todos", ...Array.from(new Set(jobs.map((job) => job.mode).filter(Boolean)))], [jobs]);
  const filtered = useMemo(() => jobs.filter((job) => { const text = `${job.title} ${job.company} ${job.place} ${job.description ?? ""} ${job.requirements ?? ""}`.toLowerCase(); const salaryOk = salary === "any" || (salary === "low" && (job.salaryKz ?? 0) > 0 && (job.salaryKz ?? 0) <= 250000) || (salary === "mid" && (job.salaryKz ?? 0) >= 250000 && (job.salaryKz ?? 0) <= 450000) || (salary === "high" && (job.salaryKz ?? 0) > 450000); const experienceOk = experience === "any" || (experience === "junior" && (job.experienceYears ?? 0) <= 2) || (experience === "mid" && (job.experienceYears ?? 0) >= 3 && (job.experienceYears ?? 0) <= 5) || (experience === "senior" && (job.experienceYears ?? 0) >= 6); return text.includes(query.toLowerCase()) && (area === "Todas" || job.area === area) && (mode === "Todos" || job.mode === mode) && salaryOk && experienceOk; }), [jobs, query, area, mode, salary, experience]);
  return <main><Header /><section className="catalog-hero"><p className="eyebrow">Oportunidades OkutiJobs</p><h1>Encontre o próximo<br /><em>movimento.</em></h1><p className="lede">Pesquise oportunidades reais por função, área, localização e regime de trabalho.</p><div className="catalog-filters"><input aria-label="Pesquisar vagas" placeholder="Cargo, competência ou empresa" value={query} onChange={(e) => setQuery(e.target.value)} /><select aria-label="Filtrar por área" value={area} onChange={(e) => setArea(e.target.value)}>{areas.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filtrar por regime" value={mode} onChange={(e) => setMode(e.target.value)}>{modes.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filtrar por salário" value={salary} onChange={(e) => setSalary(e.target.value)}><option value="any">Qualquer salário</option><option value="low">Até 250.000 Kz</option><option value="mid">250.000–450.000 Kz</option><option value="high">Mais de 450.000 Kz</option></select><select aria-label="Filtrar por experiência" value={experience} onChange={(e) => setExperience(e.target.value)}><option value="any">Qualquer experiência</option><option value="junior">Até 2 anos</option><option value="mid">3–5 anos</option><option value="senior">6+ anos</option></select></div></section><section className="catalog-section"><div className="section-heading"><div><p className="eyebrow">{filtered.length} resultados reais</p><h2>Vagas disponíveis.</h2></div><Link className="button button-orange" href="/profile">Criar perfil candidato <span>↗</span></Link></div>{filtered.length > 0 ? <div className="catalog-grid">{filtered.map((job) => <article className="opportunity-card" key={job.id} onClick={() => setSelectedJob(job)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelectedJob(job); }}><div className="card-top"><span className="mini-icon">↗</span><span className="job-tag">{job.contract || "Oportunidade"}</span></div><p className="card-company">{job.company}</p><h3>{job.title}</h3><p className="card-place">◌ &nbsp;{job.place || "Localização não indicada"} · {job.mode || "Regime a definir"}</p>{job.area && <p className="card-meta">{job.area}</p>}<button className="card-link card-apply" onClick={(event) => { event.stopPropagation(); setSelectedJob(job); }}>Ver vaga e candidatar-me →</button></article>)}</div> : <div className="empty-state"><h3>Ainda não existem vagas publicadas.</h3><p>Quando uma empresa publicar uma oportunidade, ela aparecerá aqui. Tente ajustar os filtros ou volte mais tarde.</p></div>}</section>{selectedJob && <ApplicationModal job={selectedJob} onClose={() => setSelectedJob(null)} />}</main>;
}

export function TrainingCatalog() { return <main><Header /><section className="catalog-hero training-hero"><p className="eyebrow">Formação corporativa</p><h1>Competências que<br /><em>fazem avançar.</em></h1><p className="lede">Programas práticos para equipas mais preparadas, produtivas e alinhadas com o futuro do trabalho.</p></section><section className="catalog-section"><div className="section-heading"><div><p className="eyebrow">Catálogo OkutiJobs</p><h2>Aprendizagem aplicada.</h2></div><Link className="button button-dark" href="/pagina-empresas">Solicitar formação <span>↗</span></Link></div><div className="course-grid">{courses.map((course) => <article className="course-card" key={course.title}><span className="course-area">{course.area}</span><h3>{course.title}</h3><p>{course.level} · {course.mode}</p><strong>{course.duration}</strong><Link href="/pagina-empresas">Saber mais <span>↗</span></Link></article>)}</div></section></main>; }

export function ServicesPage({ audience }: { audience: "candidate" | "company" }) { const candidate = audience === "candidate"; return <main><Header /><section className="catalog-hero"><p className="eyebrow">{candidate ? "Para profissionais" : "Soluções para empresas"}</p><h1>{candidate ? <>O seu talento<br /><em>merece ser visto.</em></> : <>Equipas mais fortes começam com <em>decisões melhores.</em></>}</h1><p className="lede">{candidate ? "Ferramentas, orientação e oportunidades para construir o próximo capítulo da sua carreira." : "Recrutamento, avaliação, formação e inteligência de talento para organizações em crescimento."}</p></section><section className="catalog-section"><div className="service-grid">{(candidate ? ["Perfil profissional", "Revisão de CV por IA", "Oportunidades compatíveis", "Formações de carreira"] : ["Recrutamento especializado", "Banco de talentos", "Avaliação e testes", "Okuti Career AI", "Formação corporativa"]).map((title, i) => <article className="service-card" key={title}><span className="service-number">0{i + 1}</span><h3>{title}</h3><p>{candidate ? "Apresente melhor as suas competências e encontre oportunidades com mais contexto." : "Decisões de talento mais simples, humanas e inteligentes para a sua organização."}</p><Link href={candidate && i === 1 ? "/profile" : "/login"}>{candidate ? "Começar agora" : "Solicitar proposta"} <span>↗</span></Link></article>)}</div></section></main>; }

export function JobDetailView({ job }: { job: Job }) {
  const [open, setOpen] = useState(false);
  const requirements = (job.requirements || "Os requisitos serão apresentados pela empresa durante o processo.").split(/[\n;•]+/).map((item) => item.trim()).filter(Boolean);
  return <main><Header /><section className="job-detail-hero"><Link className="back-link" href="/vagas">← Voltar às vagas</Link><p className="eyebrow">{job.company}</p><h1>{job.title}</h1><div className="job-detail-facts"><span>{job.place || "Angola"}</span><span>{job.mode || "Regime a confirmar"}</span><span>{job.contract || "Oportunidade"}</span>{job.area && <span>{job.area}</span>}</div><button className="button button-orange job-detail-cta" onClick={() => setOpen(true)}>Candidatar-me a esta vaga <span>↗</span></button></section><section className="job-detail-body"><article><p className="eyebrow">Descrição da função</p><div className="detail-copy">{(job.description || "Conheça esta oportunidade e veja como o seu perfil pode contribuir.").split(". ").map((sentence, index) => <p key={index}>{sentence}{sentence.endsWith(".") ? "" : "."}</p>)}</div></article><aside className="job-detail-aside"><p className="eyebrow">Requisitos da vaga</p><ul className="requirements-list">{requirements.map((requirement, index) => <li key={`${requirement}-${index}`}>{requirement}</li>)}</ul><div className="detail-contact"><strong>Pronto para avançar?</strong><span>Candidate-se com o seu perfil e CV privado através do formulário seguro OkutiJobs.</span><button className="button button-orange" onClick={() => setOpen(true)}>Enviar candidatura <span>↗</span></button></div></aside></section>{open && <ApplicationModal job={job} onClose={() => setOpen(false)} />}</main>;
}
