"use client";

import { useMemo, useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";

export type CompanyJobStat = { id: string; title: string; status: string; applications: number };

function Header({ kind }: { kind: "candidate" | "company" }) { return <SiteHeader signedIn accountHref={kind === "candidate" ? "/candidato" : "/empresa"} />; }

const candidateLinks = [{ label: "Oportunidades compatíveis", href: "/vagas", note: "6 vagas disponíveis" }, { label: "O meu perfil", href: "/profile", note: "Complete os seus dados" }, { label: "As minhas candidaturas", href: "/candidato/candidaturas", note: "Acompanhe o seu percurso" }, { label: "Revisão de CV por IA", href: "/profile", note: "Disponível ao carregar um CV" }];
const companyLinks = [{ label: "Criar nova oferta", href: "/pagina-empresas", note: "Publique uma oportunidade" }, { label: "Ofertas de emprego", href: "/vagas", note: "Gerir vagas publicadas" }, { label: "Candidaturas recebidas", href: "/empresa/candidaturas", note: "Consultar perfis e CVs" }, { label: "Banco de talentos", href: "/pagina-empresas", note: "Pesquisar perfis compatíveis" }, { label: "Formação corporativa", href: "/formacoes", note: "Desenvolver a sua equipa" }];

function CompanyAnalytics({ stats }: { stats: CompanyJobStat[] }) {
  const total = stats.reduce((sum, job) => sum + job.applications, 0);
  const published = stats.filter((job) => job.status === "published").length;
  const top = Math.max(...stats.map((job) => job.applications), 1);
  return <section className="company-analytics" aria-labelledby="analytics-title"><div className="analytics-heading"><div><p className="eyebrow">Desempenho das ofertas</p><h2 id="analytics-title">Candidaturas por vaga.</h2><p>Acompanhe o interesse recebido e identifique rapidamente as oportunidades com maior procura.</p></div><span className="analytics-live">Dados Supabase · actualizado agora</span></div><div className="analytics-kpis"><div><strong>{total}</strong><span>Candidaturas recebidas</span></div><div><strong>{published}</strong><span>Ofertas publicadas</span></div><div><strong>{stats.length ? Math.round(total / stats.length) : 0}</strong><span>Média por vaga</span></div></div>{stats.length ? <div className="analytics-bars">{stats.map((job) => <div className="analytics-row" key={job.id}><div className="analytics-row-label"><span title={job.title}>{job.title}</span><strong>{job.applications}</strong></div><div className="analytics-track"><span style={{ width: `${Math.max((job.applications / top) * 100, job.applications ? 8 : 0)}%` }} /></div></div>)}</div> : <div className="analytics-empty"><strong>Ainda não existem dados de candidaturas.</strong><span>Publique uma oferta para começar a acompanhar o desempenho aqui.</span></div>}</section>;
}

export function PortalDashboard({ kind, email, companyStats = [] }: { kind: "candidate" | "company"; email: string; companyStats?: CompanyJobStat[] }) {
  const candidate = kind === "candidate";
  const links = candidate ? candidateLinks : companyLinks;
  const [notice, setNotice] = useState<string | null>(null);
  const analytics = useMemo(() => companyStats, [companyStats]);
  return <main><Header kind={kind} /><section className="portal-wrap"><div className="portal-heading"><div><p className="eyebrow">Área {candidate ? "do candidato" : "da empresa"}</p><h1>{candidate ? "O seu próximo passo começa aqui." : "A sua equipa começa aqui."}</h1><p className="lede">{email} · Sessão protegida por Supabase</p></div><span className="portal-status">● Conta activa</span></div><div className="portal-grid"><article className="portal-summary"><p className="eyebrow">Resumo</p><h2>{candidate ? "Perfil em construção." : "Organização em crescimento."}</h2><p>{candidate ? "Quanto mais completo estiver o seu perfil, melhores serão as recomendações de oportunidades." : "Complete os dados da sua organização para apresentar uma presença mais forte aos candidatos."}</p><div className="progress-track"><span style={{ width: candidate ? "42%" : "34%" }} /></div><strong>{candidate ? "42%" : "34%"} completo</strong><a className="button button-orange" href={candidate ? "/profile" : "/pagina-empresas"}>Completar perfil <span>↗</span></a></article><div className="portal-actions">{links.map((link, index) => <a className="portal-action" href={link.href} key={link.label}><span className="portal-index">0{index + 1}</span><span><strong>{link.label}</strong><small>{link.note}</small></span><b>↗</b></a>)}</div></div>{!candidate && <CompanyAnalytics stats={analytics} />}<section className="portal-lower"><div><p className="eyebrow">Actividade recente</p><h2>{candidate ? "Continue a explorar." : companyStats.length ? "As suas ofertas estão activas." : "Ainda não publicou ofertas."}</h2><p>{candidate ? "Explore as vagas e candidate-se às oportunidades que combinam consigo." : companyStats.length ? "Consulte as candidaturas recebidas e acompanhe cada processo a partir do painel." : "Crie a primeira oferta para começar a receber candidatos compatíveis."}</p></div><div className="portal-note"><span>◌</span><p>{notice ?? "As notificações e os dados reais serão ligados a este painel na próxima etapa da migração."}</p>{!notice && <button onClick={() => setNotice("Notificação marcada como lida.")}>Marcar como lida</button>}</div></section></section></main>;
}
