import { SiteHeader } from "@/components/SiteHeader";
import { FlatIllustration } from "@/components/FlatIllustration";
import { CvReviewExperience } from "@/components/CvReviewExperience";
function Header() { return <SiteHeader />; }
const partners = ["Pregestor", "Basel Angola", "Manguinvestimentos", "Gestgráfica", "Logpalanca", "Tiffany", "Empório das Bromélias", "Editora das Letras", "Valsantos", "Omarf Tratores", "Fisioprevine"];
export function PartnersPage() { return <main><Header /><section className="catalog-hero"><p className="eyebrow">Relações que criam impacto</p><h1>Empresas que confiam<br /><em>no talento certo.</em></h1><p className="lede">Apoiamos organizações de referência no mercado angolano a encontrar, desenvolver e reter as suas melhores pessoas.</p></section><section className="catalog-section"><div className="partner-list">{partners.map((partner, i) => <article key={partner}><span>0{i + 1}</span><h2>{partner}</h2><p>Organização parceira OkutiJobs</p></article>)}</div></section></main>; }
export function AboutPage() { return <main><Header /><section className="catalog-hero"><p className="eyebrow">Sobre a OkutiJobs</p><h1>Talento local.<br /><em>Impacto global.</em></h1><p className="lede">Somos uma plataforma angolana de recrutamento e desenvolvimento profissional que aproxima pessoas e organizações através de tecnologia, contexto e acompanhamento humano.</p></section><section className="catalog-section about-visual-section"><div className="about-illustration-wrap"><FlatIllustration className="flat-section-illustration" src="/manus-storage/okutijobs-flat-about-highfive_a646de91.png" alt="Três profissionais a celebrar uma conquista conjunta com um high-five junto a uma mesa" /></div><div className="info-columns about-copy"><div><p className="eyebrow">A nossa visão</p><h2>Um mercado de trabalho mais acessível, preparado e conectado.</h2></div><div><p>Ajudamos candidatos a apresentar melhor as suas competências e empresas a tomar decisões de talento mais informadas. A inteligência artificial apoia o processo; a avaliação humana continua essencial.</p><p>Construímos para Angola e para profissionais que querem alcançar oportunidades sem fronteiras.</p></div></div></section></main>; }
export function PrivacyPage() { return <main><Header /><section className="catalog-hero"><p className="eyebrow">Privacidade e confiança</p><h1>Os seus dados merecem<br /><em>responsabilidade.</em></h1><p className="lede">Esta página resume como a OkutiJobs trata dados de candidatos, empresas, documentos e comunicações.</p></section><section className="catalog-section policy-grid">{[["Que dados recolhemos?", "Dados de conta, perfil profissional, candidaturas e documentos que o utilizador decide carregar."],["Como usamos os dados?", "Para disponibilizar perfis, vagas, candidaturas, recomendações e serviços solicitados."],["Os CVs são públicos?", "Não. Os documentos ficam em armazenamento privado e o acesso é temporário e autorizado."],["Posso controlar comunicações?", "Sim. Consentimentos de email, SMS e WhatsApp devem ser separados e podem ser revogados."],["As empresas vêem tudo?", "Não. O acesso deve respeitar a finalidade, o perfil público e as regras de autorização da plataforma."],["Como exercer os meus direitos?", "Contacte a OkutiJobs para solicitar acesso, correção, exportação ou eliminação dos seus dados."]].map(([title, text]) => <article key={title}><h2>{title}</h2><p>{text}</p></article>)}</section></main>; }
export function CvReviewPage() { return <main><Header /><section className="catalog-hero"><p className="eyebrow">Okuti Career AI · Gemini</p><h1>Um CV melhor começa<br /><em>com uma análise honesta.</em></h1><p className="lede">Anexe o seu CV ou escreva o seu percurso profissional. Receba uma pontuação, estatísticas claras, pontos fortes, lacunas e recomendações práticas.</p></section><CvReviewExperience /></main>; }
