"use client";

import { useMemo, useState } from "react";

type Query = Record<string, string | string[] | undefined>;
type Props = { query: Query; resultCount: number };
const valueOf = (query: Query, key: string) => { const value = query[key]; return Array.isArray(value) ? value[0] ?? "" : value ?? ""; };
const groups = [
  { id: "base", title: "Pesquisa base", fields: ["q", "location", "studyField", "skills", "seniority", "workMode", "language"] },
  { id: "skills", title: "Competências e formação", fields: ["skills", "studyField", "language", "internationalCert"] },
  { id: "experience", title: "Experiência e disponibilidade", fields: ["minExperience", "driving", "passport", "maritime", "excel", "primavera", "immediate", "workMode"] },
  { id: "salary", title: "Remuneração", fields: ["currency", "minSalary", "maxSalary"] },
];
const labels: Record<string, string> = { q: "Cargo ou palavra-chave", location: "Localização", studyField: "Formação", skills: "Competências", seniority: "Senioridade", workMode: "Regime de trabalho", language: "Idiomas", minExperience: "Experiência mínima", driving: "Carta de condução", passport: "Passaporte", maritime: "Experiência marítima", excel: "Experiência com Excel", primavera: "Experiência com Primavera", internationalCert: "Certificação internacional", immediate: "Disponibilidade imediata", currency: "Moeda", minSalary: "Remuneração mínima", maxSalary: "Remuneração máxima" };
const options: Record<string, { value: string; label: string }[]> = {
  seniority: ["Estágio", "Júnior", "Pleno", "Sénior", "Gestão"].map((v) => ({ value: v, label: v })), workMode: ["Presencial", "Híbrido", "Remoto"].map((v) => ({ value: v, label: v })), language: ["Português", "Inglês", "Francês"].map((v) => ({ value: v, label: v })), minExperience: [["1", "1+ ano"], ["3", "3+ anos"], ["5", "5+ anos"], ["8", "8+ anos"], ["10", "10+ anos"]].map(([value, label]) => ({ value, label })), currency: ["AOA", "USD"].map((v) => ({ value: v, label: v })), driving: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), passport: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), maritime: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), excel: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), primavera: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), internationalCert: [["yes", "Tem"], ["no", "Não tem"]].map(([value, label]) => ({ value, label })), immediate: [["yes", "Disponível já"], ["no", "Outra disponibilidade"]].map(([value, label]) => ({ value, label })), };

export function TalentFiltersDrawer({ query, resultCount }: Props) {
  const [open, setOpen] = useState(false);
  const [criterion, setCriterion] = useState("");
  const active = Object.entries(query).filter(([key, value]) => value && key !== "page").map(([key, value]) => ({ key, value: Array.isArray(value) ? value[0] : value as string }));
  const visibleGroups = useMemo(() => groups.map((group) => ({ ...group, fields: group.fields.filter((field) => !criterion || labels[field].toLocaleLowerCase().includes(criterion.toLocaleLowerCase())) })).filter((group) => group.fields.length), [criterion]);
  const input = (name: string) => <label className="talent-drawer-field"><span>{labels[name]}</span>{options[name] ? <select name={name} defaultValue={valueOf(query, name)}><option value="">Todos</option>{options[name].map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={name} type={name.includes("Salary") ? "number" : "text"} defaultValue={valueOf(query, name)} placeholder={name === "q" ? "Ex.: contabilidade" : name === "skills" ? "Excel, liderança, Primavera" : name === "location" ? "País, província ou cidade" : "Pesquisar..."} />}</label>;
  const renderField = (name: string) => <span key={name}>{input(name)}</span>;
  return <section className={`talent-drawer-shell${open ? " is-open" : ""}`}><button type="button" className="talent-drawer-trigger" onClick={() => setOpen(true)} aria-expanded={open}><span>Filtrar candidatos</span><strong>{active.length} activos</strong><b>☷</b></button><div className="talent-drawer-backdrop" onClick={() => setOpen(false)} /><aside className="talent-drawer" aria-label="Filtros de candidatos"><header className="talent-drawer-header"><div><p className="eyebrow">Pesquisa avançada</p><h2>Encontrar candidatos.</h2><p>Combine critérios para encontrar perfis mais próximos da sua necessidade.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar filtros">×</button></header><form method="get" className="talent-drawer-form"><div className="talent-drawer-search"><span>Localizar um critério</span><input value={criterion} onChange={(event) => setCriterion(event.target.value)} placeholder="Ex.: Excel, salário, localização" /></div>{active.length > 0 && <div className="talent-active-chips"><span>Filtros aplicados</span><div>{active.map((item) => <a key={item.key} href="/empresa/talentos" title="Remover filtro">{labels[item.key] ?? item.key}: {item.value} ×</a>)}</div></div>}{visibleGroups.map((group, index) => <details className="talent-drawer-group" key={group.id} open={index < 2}><summary><strong>{group.title}</strong><span>{group.fields.filter((field) => valueOf(query, field)).length} seleccionados</span></summary><div className="talent-drawer-group-content">{group.fields.map(renderField)}{group.id === "base" && <label className="talent-drawer-field"><span>Província / localização exacta</span><input name="province" defaultValue={valueOf(query, "province")} placeholder="Ex.: Luanda" /></label>}{group.id === "skills" && <label className="talent-drawer-field"><span>Certificações e ferramentas</span><input name="certifications" defaultValue={valueOf(query, "certifications")} placeholder="Ex.: PMP, ACCA, SAP" /></label>}</div></details>)}<footer className="talent-drawer-footer"><a href="/empresa/talentos">Repor filtros</a><button className="button button-orange" type="submit">Ver {resultCount || 24} candidatos <span>→</span></button></footer></form></aside></section>;
}
