type MessageContent = string | Array<{ type: "text"; text: string } | { type: "file_url"; file_url: { url: string; mime_type?: string } }>;
type LlmResponse = { choices?: Array<{ message?: { content?: string } }> };

const stringArray = { type: "array", items: { type: "string" } } as const;
const experienceSchema = { type: "array", items: { type: "object", additionalProperties: false, properties: { role: { type: "string" }, company: { type: "string" }, industry: { type: "string" }, location: { type: "string" }, start: { type: "string" }, end: { type: "string" }, current: { type: "boolean" }, achievements: { type: "string" }, tools: { type: "string" } }, required: ["role", "company", "industry", "location", "start", "end", "current", "achievements", "tools"] } } as const;
const educationSchema = { type: "array", items: { type: "object", additionalProperties: false, properties: { level: { type: "string" }, field: { type: "string" }, institution: { type: "string" }, country: { type: "string" }, start: { type: "string" }, end: { type: "string" }, current: { type: "boolean" } }, required: ["level", "field", "institution", "country", "start", "end", "current"] } } as const;
const certificateSchema = { type: "array", items: { type: "object", additionalProperties: false, properties: { name: { type: "string" }, kind: { type: "string", enum: ["course", "competency"] }, institution: { type: "string" }, issued: { type: "string" }, expiry: { type: "string" }, credential: { type: "string" }, documentName: { type: "string" }, documentId: { type: "string" }, confirmed: { type: "boolean" } }, required: ["name", "kind", "institution", "issued", "expiry", "credential", "documentName", "documentId", "confirmed"] } } as const;
const skillSchema = { type: "array", items: { type: "object", additionalProperties: false, properties: { name: { type: "string" }, level: { type: "string" } }, required: ["name", "level"] } } as const;
const languageSchema = { type: "array", items: { type: "object", additionalProperties: false, properties: { language: { type: "string" }, level: { type: "string" }, cefr: { type: "string" } }, required: ["language", "level", "cefr"] } } as const;

export async function invokeLlm(messages: Array<{ role: "system" | "user"; content: MessageContent }>) {
  const baseUrl = process.env.BUILT_IN_FORGE_API_URL?.replace(/\/$/, "") || "https://forge.manus.im";
  const apiKey = process.env.BUILT_IN_FORGE_API_KEY;
  if (!apiKey) throw new Error("LLM não está configurado no ambiente server-side.");
  const schema = { type: "object", additionalProperties: false, properties: {
    fullName: { type: "string" }, headline: { type: "string" }, bio: { type: "string" }, currentTitle: { type: "string" }, desiredJobTitle: { type: "string" }, seniorityLevel: { type: "string" }, country: { type: "string" }, province: { type: "string" }, city: { type: "string" }, municipality: { type: "string" }, academicLevel: { type: "string" }, studyField: { type: "string" }, emailPrimary: { type: "string" }, phoneWhatsapp: { type: "string" }, linkedinUrl: { type: "string" }, websiteUrl: { type: "string" }, nationality: { type: "string" }, placeOfBirth: { type: "string" }, dateOfBirth: { type: "string" }, passportNumber: { type: "string" }, passportExpiry: { type: "string" }, passportIssuer: { type: "string" }, drivingCategories: stringArray, maritimeBookNumber: { type: "string" }, maritimeRole: { type: "string" }, certifications: stringArray, languages: stringArray, experience: stringArray, education: stringArray, skills: stringArray, softSkills: stringArray, portfolioUrl: { type: "string" }, experiencesStructured: experienceSchema, educationStructured: educationSchema, certificationsStructured: certificateSchema, hardSkills: skillSchema, languageItems: languageSchema,
  }, required: ["fullName", "headline", "bio", "currentTitle", "desiredJobTitle", "seniorityLevel", "country", "province", "city", "municipality", "academicLevel", "studyField", "emailPrimary", "phoneWhatsapp", "linkedinUrl", "websiteUrl", "nationality", "placeOfBirth", "dateOfBirth", "passportNumber", "passportExpiry", "passportIssuer", "drivingCategories", "maritimeBookNumber", "maritimeRole", "certifications", "languages", "experience", "education", "skills", "softSkills", "portfolioUrl", "experiencesStructured", "educationStructured", "certificationsStructured", "hardSkills", "languageItems"] } as const;
  const response = await fetch(`${baseUrl}/v1/chat/completions`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ messages, response_format: { type: "json_schema", json_schema: { name: "candidate_cv_international", strict: true, schema } } }) });
  if (!response.ok) throw new Error(`Falha na análise do CV (${response.status}).`);
  const result = (await response.json()) as LlmResponse; const content = result.choices?.[0]?.message?.content;
  if (!content) throw new Error("O analisador não devolveu dados.");
  return JSON.parse(content) as Record<string, unknown>;
}
