import { notFound, redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type PageProps = { params: Promise<{ id: string }> };
type Candidate = { id: string; headline: string | null; bio: string | null; desired_job_title: string | null; current_title: string | null; seniority_level: string | null; country: string | null; province: string | null; city: string | null; academic_level: string | null; study_field: string | null; skills: unknown; certifications: unknown; languages: unknown; experience: unknown; education: unknown; salary_currency: string | null; salary_min_amount: number | null; salary_max_amount: number | null; visibility: string; open_to_work: boolean };
function values(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }

export default async function TalentProfilePage({ params }: PageProps) {
  const supabase = await createSupabaseServerClient();
  const { data: auth } = supabase ? await supabase.auth.getUser() : { data: { user: null } };
  if (!auth.user) redirect("/login");
  const { id } = await params;
  const [{ data: candidate }, { data: profile }] = await Promise.all([
    supabase!.from("candidate_profiles").select("*").eq("id", id).eq("visibility", "public").eq("open_to_work", true).maybeSingle(),
    supabase!.from("profiles").select("full_name").eq("id", id).maybeSingle(),
  ]);
  if (!candidate) notFound();
  const data = candidate as Candidate;
  return <main><header className="site-header"><a href="/empresa/talentos" className="brand" aria-label="Voltar ao Banco de talentos"><span className="brand-mark">O</span>Okuti<span className="brand-accent">Jobs</span></a><nav className="desktop-nav" aria-label="Navegação empresarial"><a href="/empresa">Painel</a><a href="/empresa/talentos">Banco de talentos</a><a href="/empresa/candidaturas">Candidaturas</a></nav><div className="header-actions"><a className="button button-dark header-cta" href="/empresa/talentos">Voltar à pesquisa <span>↗</span></a></div></header><section className="portal-wrap talent-profile-page"><a className="text-link" href="/empresa/talentos">← Banco de talentos</a><div className="talent-profile-hero"><div><p className="eyebrow">Perfil público autorizado</p><h1>{profile?.full_name || "Candidato"}</h1><p className="profile-title">{data.current_title || data.desired_job_title || data.headline || "Profissional disponível"}</p><p className="received-meta">{[data.seniority_level, data.city, data.province, data.country].filter(Boolean).join(" · ")}</p></div><span className="profile-open">● Disponível para oportunidades</span></div><div className="talent-profile-layout"><article className="talent-profile-main"><section><p className="eyebrow">Resumo</p><p className="profile-copy">{data.bio || "O candidato ainda não adicionou um resumo profissional."}</p></section><section><p className="eyebrow">Experiência profissional</p>{values(data.experience).length ? <div className="profile-list">{values(data.experience).map((item) => <p key={item}>{item}</p>)}</div> : <p className="profile-muted">Experiência detalhada não indicada.</p>}</section><section><p className="eyebrow">Formação académica</p>{values(data.education).length ? <div className="profile-list">{values(data.education).map((item) => <p key={item}>{item}</p>)}</div> : <p className="profile-muted">Formação detalhada não indicada.</p>}</section></article><aside className="talent-profile-aside"><div><strong>Competências</strong><div className="talent-skills">{values(data.skills).map((skill) => <span key={skill}>{skill}</span>)}</div></div><div><strong>Certificações</strong><p>{values(data.certifications).join(" · ") || "Não indicadas"}</p></div><div><strong>Idiomas</strong><p>{values(data.languages).join(" · ") || "Não indicados"}</p></div><div><strong>Pretensão indicativa</strong><p>{data.salary_min_amount || data.salary_max_amount ? `${data.salary_currency || "AOA"} ${data.salary_min_amount ?? "—"} – ${data.salary_max_amount ?? "—"}` : "Não indicada"}</p><small>Valor informado pelo candidato; confirme durante o processo.</small></div></aside></div></section></main>;
}
