"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

export default function NewCompanyJobPage() {
  const [form, setForm] = useState({ title: "", description: "", requirements: "", country: "Angola", province: "", city: "", work_mode: "", contract_type: "" });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(null); setError(null); const response = await fetch("/api/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(result.error ?? "Não foi possível guardar a vaga."); else setMessage("Vaga guardada como rascunho. Pode revê-la antes de publicar."); }
  return <main className="new-job-page"><div className="new-job-shell"><Link href="/empresa" className="back-link">← Voltar ao painel</Link><header className="new-job-hero"><div><p className="eyebrow">Nova oportunidade</p><h1>Encontre a pessoa certa para a sua equipa.</h1><p>Preencha o perfil da vaga com clareza. A oferta ficará guardada como rascunho para revisão antes da publicação.</p></div><span className="new-job-icon">↗</span></header><form className="new-job-form" onSubmit={submit}><section><div className="new-job-heading"><span>01</span><div><h2>Perfil da função</h2><p>Apresente a oportunidade e o que a pessoa irá fazer.</p></div></div><label><span>Título da vaga *</span><input value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="Ex.: Gestor de Marketing" required /></label><label><span>Descrição da vaga *</span><textarea rows={9} value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="Descreva responsabilidades, objectivos, equipa, benefícios e contexto da função." required /></label><label><span>Requisitos e perfil procurado</span><textarea rows={7} value={form.requirements} onChange={(e) => update("requirements", e.target.value)} placeholder="Formação, experiência, competências técnicas, idiomas e outros requisitos." /></label></section><section><div className="new-job-heading"><span>02</span><div><h2>Localização e condições</h2><p>Ajude os candidatos a compreenderem o modelo da oportunidade.</p></div></div><div className="new-job-grid"><label><span>País</span><input value={form.country} onChange={(e) => update("country", e.target.value)} /></label><label><span>Província</span><input value={form.province} onChange={(e) => update("province", e.target.value)} placeholder="Ex.: Luanda" /></label><label><span>Cidade / município</span><input value={form.city} onChange={(e) => update("city", e.target.value)} placeholder="Ex.: Viana" /></label><label><span>Modelo de trabalho</span><select value={form.work_mode} onChange={(e) => update("work_mode", e.target.value)}><option value="">Seleccionar</option><option>Presencial</option><option>Híbrido</option><option>Remoto</option></select></label><label><span>Tipo de contrato</span><select value={form.contract_type} onChange={(e) => update("contract_type", e.target.value)}><option value="">Seleccionar</option><option>Tempo inteiro</option><option>Tempo parcial</option><option>Estágio</option><option>Consultoria / Freelance</option></select></label></div></section>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}<div className="new-job-actions"><Link href="/empresa" className="button button-outline">Cancelar</Link><button className="button button-orange" disabled={busy}>{busy ? "A guardar…" : "Guardar rascunho ↗"}</button></div></form></div></main>;
}
